581 update admin UI implementation to make meta functionality reusable
TNO/knowledge-engine pull request #583
Opened 2024-12-20 08:52 UTC by bnouwt

2025-01-10 10:00 UTC, Sophietje requested changes

2025-01-10 10:00 UTC, Sophietje commented on admin-ui/src/main/java/eu/knowledge/engine/admin/AdminUI.java
> +		if (continuousLog) {
A lot of the methods in this class use the same way to log the knowledge bases to the console. Perhaps move this to a separate method and call that in each method?
Methods in which the logging is now called in a similar way: `handleNewKnowledgeBaseKnowledge`, `handleChangedKnowledgeBaseKnowledge`, `handleRemovedKnowledgeBaseKnowledge`, and `fetchInitialData`.

2025-01-10 10:00 UTC, Sophietje commented on admin-ui/src/main/java/eu/knowledge/engine/admin/MetadataKB.java
> +	 * Intialize a AdminUI that regularly retrieves and prints metadata about the
Is this documentation still correct, MetaKB is now separate from the Admin UI right?

2025-01-10 10:00 UTC, Sophietje commented on admin-ui/src/main/java/eu/knowledge/engine/admin/MetadataKB.java
> +				LOG.info("{}", e);
Could we improve the error message here rather than just printing the exception?

2025-01-10 10:00 UTC, Sophietje commented on admin-ui/src/main/java/eu/knowledge/engine/admin/MetadataKB.java
> +			// this we can simply add to our model
I would remove this comment as it adds little/no information

2025-01-10 10:00 UTC, Sophietje commented on smart-connector/src/main/java/eu/knowledge/engine/smartconnector/util/EasyKnowledgeBase.java
> +public class EasyKnowledgeBase implements KnowledgeBase {
I'm not sure about the name `EasyKnowledgeBase` as it's unclear what 'easy' means in this context. We could try `KnowledgeBaseImpl` which is a convention we're using in other parts of the repo where a class is an implementation of an interface? I'm still thinking about other alternatives that we could use.

2025-01-10 10:00 UTC, Sophietje commented on admin-ui/src/main/java/eu/knowledge/engine/admin/AdminUI.java
>  	public BindingSet handleNewKnowledgeBaseKnowledge(ReactExchangeInfo ei) {
I find the name of this method a bit convoluted, what does "New Knowledge Base Knowledge" mean?
Would something like "handleNewKnowledgeBase" still be accurate?
Similar remarks for the Changed-/RemovedNewKnowledgeBaseKnowledge methods

2025-01-10 10:00 UTC, Sophietje commented on admin-ui/src/main/java/eu/knowledge/engine/admin/AdminUI.java
> +		// when result available (and the config is enabled), we print the
I think this comment about logging is unnecessary and can be removed

2025-01-10 16:39 UTC, bnouwt commented on admin-ui/src/main/java/eu/knowledge/engine/admin/AdminUI.java
> +		if (continuousLog) {
Aha, good point! You mean a method which includes the `if (continuousLog) {` part as well? Or do you mean something else?

2025-01-10 16:40 UTC, bnouwt commented on admin-ui/src/main/java/eu/knowledge/engine/admin/MetadataKB.java
> +	 * Intialize a AdminUI that regularly retrieves and prints metadata about the
You are correct, I need to modify that 👍

2025-01-10 16:40 UTC, bnouwt commented on admin-ui/src/main/java/eu/knowledge/engine/admin/MetadataKB.java
> +				LOG.info("{}", e);
I will 👍

2025-01-10 16:40 UTC, bnouwt commented on admin-ui/src/main/java/eu/knowledge/engine/admin/MetadataKB.java
> +			// this we can simply add to our model
Agree.

2025-01-10 16:44 UTC, bnouwt commented on smart-connector/src/main/java/eu/knowledge/engine/smartconnector/util/EasyKnowledgeBase.java
> +public class EasyKnowledgeBase implements KnowledgeBase {
Yes, I agree `Easy` is not very descriptive 😄 . But `KnowledgeBaseImpl` would also not be that descriptive. The purpose of this class is to make it easier to create a knowledge base. co-pilot says the following:

- SimpleKnowledgeBase
- QuickKnowledgeBase
- KnowledgeBaseHelper
- KnowledgeBaseBuilder
- ConvenientKnowledgeBase
- KnowledgeBaseManager
- EffortlessKnowledgeBase

2025-01-13 08:26 UTC, Sophietje commented on admin-ui/src/main/java/eu/knowledge/engine/admin/AdminUI.java
> +		if (continuousLog) {
Yes, I mean the `if(....) { this.print... }`

2025-01-13 08:42 UTC, Sophietje commented on smart-connector/src/main/java/eu/knowledge/engine/smartconnector/util/EasyKnowledgeBase.java
> +public class EasyKnowledgeBase implements KnowledgeBase {
It's true that KnowledgeBaseImpl is not that descriptive either, but at least we would then be using the same convention as in the rest of the repo. Another name would be fine as well. I'm not sure about the above ones though, my preferred ones would be the KnowledgeBaseBuilder or KnowledgeBaseManager, but neither seems to fit great. With KnowledgeBaseBuilder I would expect a method that returns a KnowledgeBase object, rather than a class that implements the interface. With KnowledgeBaseManager I would expect it to manage multiple instances rather than a single KnowledgeBase. 

For now maybe just choose a name you like, and perhaps we should reconsider our design for making new Knowledge Base implementations. Maybe we can use something like the Factory or Builder pattern to refactor it later?

2025-01-13 08:45 UTC, bnouwt commented on smart-connector/src/main/java/eu/knowledge/engine/smartconnector/util/EasyKnowledgeBase.java
> +public class EasyKnowledgeBase implements KnowledgeBase {
Let's go with `KnowledgeBaseImpl` 👍

2025-01-13 08:51 UTC, bnouwt commented on admin-ui/src/main/java/eu/knowledge/engine/admin/AdminUI.java
> +		if (continuousLog) {
I've moved the `if (continuousLog)` statement inside the `print...` method.

2025-01-13 08:52 UTC, bnouwt commented on admin-ui/src/main/java/eu/knowledge/engine/admin/MetadataKB.java
> +	 * Intialize a AdminUI that regularly retrieves and prints metadata about the
Done.

2025-01-13 08:54 UTC, bnouwt commented on admin-ui/src/main/java/eu/knowledge/engine/admin/MetadataKB.java
> +				LOG.info("{}", e);
Done

2025-01-13 10:42 UTC, merged